#!/usr/bin/env node
// v0.9.4+: auto-generate `packages/core/src/version.generated.ts` from
// `package.json` so the runtime `aiftp --version` cannot drift away
// from the published npm version. The generated file is .gitignore'd
// and rebuilt on every `pnpm build` via the `prebuild` script.
//
// Before this script, the version constant was hand-edited in
// `index.ts`. The v0.9.2 cycle shipped twice with `aiftp --version`
// returning `0.0.0` because the human (Claude) forgot to bump the
// constant. v0.9.4 removes that footgun.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'src', 'version.generated.ts');

const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));
const version = pkg.version;

if (typeof version !== 'string' || !/^\d+\.\d+\.\d+(?:-[\w.]+)?$/.test(version)) {
  throw new Error(
    `generate-version: package.json version "${version}" is not a valid semver string.`,
  );
}

const out = `// AUTO-GENERATED by packages/core/scripts/generate-version.mjs.\n// DO NOT EDIT. Run \`pnpm -C packages/core build\` to regenerate.\n// Source of truth: packages/core/package.json "version".\n\nexport const VERSION = '${version}';\n`;

await writeFile(outPath, out, 'utf8');
console.log(`[generate-version] wrote ${outPath} (v${version})`);
